// pages/home.tsx
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { supabase } from "../utils/initSupabase";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Markdown from "react-markdown";
import gfm from "remark-gfm";
import Link from "next/link";
import Head from "next/head";
import ImageFallback from "react-image-fallback";
import EdiText from "react-editext";

dayjs.extend(relativeTime);
library.add(fab, fas);

export default function UserPage({ posts, user, profiles }) {
  const [post, setPost] = useState(posts.content);
  const session = supabase.auth.session();
  const [profile, setProfile] = useState([]);
  const [edit, editPost] = useState([]);

  const router = useRouter();
  // Call this function whenever you want to
  // refresh props!
  const refreshData = () => {
    router.replace(router.asPath);
  };

  useEffect(() => {
    async function fetchProfile() {
      if (user) {
        const { body, error } = await supabase
          .from("profiles")
          .select("*")
          .eq("id", session.user.id)
          .single();

        setProfile(body.avatar);
      }
    }

    fetchProfile();

    // subscription
    supabase
      .from("posts")
      .on("*", (_payload) => {
        refreshData();
      })
      .subscribe();
  }, []);

  const createPost = async (event) => {
    event.preventDefault();
    await supabase.from("posts").insert([{ content: post, user_id: user.id }]);
    setPost("");
  };

  const editPosts = async (edit, editID) => {
    await supabase
      .from("posts")
      .update({
        content: edit,
      })
      .eq("id", editID);
  };

  const deletePost = async (postID) => {
    await supabase
      .from("posts")
      .delete()
      .match({ id: `${postID}` });
  };

  const formatDate = (date: string) => {
    return dayjs().to(dayjs(date));
  };

  return (
    <>
      <Head>
        <title>Home | ollo</title>
      </Head>
      <div>
        <div className="herocont padd2 postsfeed">
          <div>
            <div></div>
            <div className="feed">
              {user && (
                <div className="cards flex">
                  <img className="avatar" src={`${profile}`} />
                  <form className="postcontainer" onSubmit={createPost}>
                    <div className="postcontainer">
                      <textarea
                        id="clearPost"
                        name="bio"
                        value={post}
                        onChange={(event) => setPost(event.target.value)}
                        placeholder="What have you done today?"
                        className="textarea postinput"
                      />
                      <button className="button postsubmit" type="submit">
                        Post
                      </button>
                      <p className="postmarkdown">
                        <FontAwesomeIcon icon={["fab", "markdown"]} /> is
                        supported
                      </p>
                    </div>
                  </form>
                </div>
              )}
              {user === null && (
                <Link href="/dashboard">
                  <div className="created2">
                    <div className="cards created">
                      <div className="create">
                        <h1 className="createTitle text-4xl">
                          Create a post, edit your ollo and do more...
                        </h1>
                        <p className="createText text-2xl p-1">
                          Create an ollo or login to make a post!
                        </p>
                        <button className="button">Get started</button>
                      </div>
                      <div className="inline2">
                        {profiles.data
                          .filter((n) => n.username)
                          .sort(() => Math.random() - Math.random())
                          .slice(0, 30)
                          .map((profile) => (
                            <div className="item">
                              <a
                                className="profileavatar"
                                href={`/${
                                  profile.username ? profile.username : ""
                                }`}
                              >
                                <ImageFallback
                                  data-tip
                                  data-for={profile.username}
                                  className="avatar avatar3"
                                  fallbackImage="avatar.png"
                                  src={profile.avatar}
                                />
                              </a>
                            </div>
                          ))}
                      </div>
                    </div>
                  </div>
                </Link>
              )}
              {posts.data.map((post, index) => (
                <div className="cards postcard">
                  <div className="flex">
                    <div className="avatarcont ml-0 mr-0">
                      <a href={`/${post.username}`}>
                        <ImageFallback
                          data-tip
                          data-for={post.username}
                          className="avatar avatar2"
                          fallbackImage="avatar.png"
                          src={post.avatar}
                        />
                      </a>
                    </div>
                    <div className="info ml-4">
                      <h1 className="username mb-2 left">
                        {post.displayname ? post.displayname : post.username}{" "}
                        <span className="handle">{post.verified ? post.verified = (
                          <span className="verify">
                          <FontAwesomeIcon icon={["fas", "check"]} />
                        </span>
                        ) : null}</span>
                        <span className="handle">@{post.username}</span>
                        <br/>
                        <a className="minutesago" href={`posts/${post.id}`}>
                          {formatDate(post.published_at)}
                        </a>
                      </h1>
                      <br/>
                      </div>
                    </div>
                    <p className="postcontent">
                        {session &&
                          (user.id === post.user_id ? (
                            <>
                              <EdiText
                                key={post.id}
                                value={post.content}
                                onSave={(value) => editPosts(value, post.id)}
                                submitOnEnter
                                type="textarea"
                                renderValue={(value) => {
                                  return (
                                    <Markdown
                                      plugins={[gfm]}
                                      children={post.content}
                                    />
                                  );
                                }}
                              />
                            </>
                          ) : (
                            <Markdown plugins={[gfm]} children={post.content} />
                          ))}
                        {session === null && (
                          <>
                          <Markdown plugins={[gfm]} children={post.content} />
                        </>
                        )}
                      </p>
                      <div className="mt-2">
                      <span className="minutesago reply">
                          reply
                        </span>
                        </div>
                  <div>
                    {session &&
                      (session.user.id === post.user_id ? (
                        <>
                          <button
                            onClick={() => deletePost(post.id)}
                            className="bg-red-500 text-gray-200 minutesago"
                          >
                            delete
                          </button>
                        </>
                      ) : (
                        <p></p>
                      ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export async function getServerSideProps({ req }) {
  const { user } = await supabase.auth.api.getUserByCookie(req);

  const profiles = await supabase.from("profiles").select("*");

  const posts = await supabase.from("vw_posts_with_user").select();

  return {
    props: {
      profiles: profiles,
      user: user,
      posts: posts,
    },
  };
}

// pages/home.vue
<template>
  <div>
    <div v-if="user" class="cards flex">
      <img class="avatar" :src="user.user_metadata.avatar_url" alt="User Avatar" />
      <form class="postcontainer" @submit.prevent="handlePostSubmit">
        <div class="postcontainer">
          <textarea
            id="clearPost"
            name="post"
            placeholder="What have you done today?"
            class="textarea postinput"
            v-model="newPost"
          />
          <button class="button postsubmit" type="submit">
            Post
          </button>
          <p class="postmarkdown">
            <font-awesome-icon :icon="['fab', 'markdown']" /> is supported
          </p>
        </div>
      </form>
      <div v-if="error" class="error">{{ error }}</div>
    </div>

    <div v-for="post in posts" :key="post.id" class="cards postcard">
      <div class="flex">
        <div class="flex-col ml-0 mr-0">
          <a :href="`/${post.username}`">
            <img class="avatar avatar3" :src="post.avatar" :alt="`${post.username} avatar`" />
          </a>
        </div>
        <div class="info flex ml-4">
          <h1 class="username mb-2 left">
            {{ post.displayname || post.username }}
            <span class="handle">
              <span v-if="post.verified" class="verify">
                <font-awesome-icon :icon="['fas', 'check']" />
              </span>
            </span>
            <span class="handle">@{{ post.username }}</span>
            <br />
            <a class="minutesago" :href="`posts/${post.id}`">
              {{ formatPostDate(post.published_at) }}
            </a>
          </h1>
          <br />
        </div>
      </div>
      <p class="postcontent grid">
        {{ post.content }}
      </p>
      <div class="replies">
        <div
          v-for="reply in replies.filter((reply) => reply.post_id === post.id)"
          :key="reply.id"
          class="postcontent mb-4"
        >
          <img
            v-if="reply.avatar"
            data-tooltip-id="avatarTooltip"
            :data-tooltip-content="reply.username"
            class="avatar avatar3"
            :src="reply.avatar"
            :alt="reply.username"
          />
          <tooltip id="avatarTooltip" />
          <p class="reply-content mt-3">{{ reply.content }}</p>
          <p>
            <span class="reply-author minutesago mt-3">
              {{ formatDate(reply.created_at) }}
            </span>
          </p>
        </div>
      </div>
      <div>
        <span class="minutesago mt-6 mr-3">
          <Like :postId="post.id" :initialLikes="post.likes" /> {{ post.likes }}
        </span>
        <button class="minutesago mr-3" @click="toggleReplyInput(post.id)">
          reply
        </button>
        <button v-if="post.author_id === user.id" @click="deletePost(post.id)" class="bg-red-500 text-gray-200 minutesago">
          delete
        </button>
      </div>
      <form v-if="replyInputs[post.id]" class="reply-form" @submit.prevent="handleReplySubmit(post.id)">
        <textarea name="reply" placeholder="Write a reply..." class="textarea reply-input" v-model="replyContent" />
        <button type="submit" class="button reply-submit">Reply</button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime);

const supabase = useSupabaseClient();
const user = useSupabaseUser();

const posts = ref([]);
const replies = ref([]);
const newPost = ref('');
const error = ref<string | null>(null);
const replyInputs = reactive<Record<number, boolean>>({});
const replyContent = ref('');

onMounted(async () => {
  await fetchPosts();
  await fetchReplies();
});

async function fetchPosts() {
  try {
    const { data, error: fetchError } = await supabase.from('posts_with_likes').select().order('id', { ascending: false });
    if (fetchError) {
      throw fetchError;
    }
    posts.value = data;
  } catch (err) {
    console.error('Error fetching posts:', err.message);
  }
}

async function fetchReplies() {
  try {
    const { data, error: fetchError } = await supabase.from('reply_with_profile').select('*').order('id', { ascending: true });
    if (fetchError) {
      throw fetchError;
    }
    replies.value = data;
  } catch (err) {
    console.error('Error fetching replies:', err.message);
  }
}

function formatDate(date: string) {
  return dayjs(date).fromNow();
}

function formatPostDate(dateString: string) {
  const date = new Date(dateString);
  const real_time = date.getTime();
  const minutesOffset = new Date().getTimezoneOffset();
  return dayjs(new Date(real_time + minutesOffset * -1 * 60 * 1000)).fromNow();
}

async function handlePostSubmit() {
  try {
    if (!user.value) {
      throw new Error('User not authenticated');
    }
    const { data, error: postError } = await supabase.from('posts').insert([{ content: newPost.value, user_id: user.value.id }]);
    if (postError) {
      throw postError;
    }
    newPost.value = '';
    await fetchPosts(); // Refresh posts after submission
    console.log('Post submitted successfully:', data);
  } catch (err) {
    error.value = 'Error submitting post: ' + err.message;
    console.error('Error submitting post:', err);
  }
}

async function editPosts(content: string, postId: number) {
  try {
    const { data, error: editError } = await supabase.from('posts').update({ content }).eq('id', postId);
    if (editError) throw editError;
    await fetchPosts(); // Refresh posts after editing
    console.log('Post updated successfully:', data);
  } catch (err) {
    error.value = 'Error updating post: ' + err.message;
    console.error('Error updating post:', err);
  }
}

async function deletePost(postId: number) {
  try {
    const { error: deleteRepliesError } = await supabase.from('replies').delete().eq('post_id', postId);
    if (deleteRepliesError) throw deleteRepliesError;

    const { data, error: deletePostError } = await supabase.from('posts').delete().eq('id', postId);
    if (deletePostError) throw deletePostError;

    await fetchPosts(); // Refresh posts after deletion
    console.log('Post and its replies deleted successfully:', data);
  } catch (err) {
    error.value = 'Error deleting post: ' + err.message;
    console.error('Error deleting post:', err);
  }
}

async function postReply(content: string, postId: number) {
  try {
    if (!user.value) {
      throw new Error('User not authenticated');
    }
    const { data, error: replyError } = await supabase.from('replies').insert([{ content, post_id: postId, user_id: user.value.id }]);
    if (replyError) throw replyError;
    await fetchReplies(); // Refresh replies after submission
    console.log('Reply submitted successfully:', data);
  } catch (err) {
    error.value = 'Error submitting reply: ' + err.message;
    console.error('Error submitting reply:', err);
  }
}

function toggleReplyInput(postId: number) {
  replyInputs[postId] = !replyInputs[postId];
}

async function handleReplySubmit(postId: number) {
  try {
    await postReply(replyContent.value, postId);
    replyContent.value = '';
  } catch (err) {
    error.value = 'Error submitting reply: ' + err.message;
    console.error('Error submitting reply:', err);
  }
}

watchEffect(() => {
  if (!user.value) {
    return navigateTo('/login')
  }
})
</script>

<style scoped>
/* Add your styles here */
</style>
