// app/routes/home.tsx
import { useState, useEffect, useContext } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { Form, useLoaderData } from "@remix-run/react";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import EdiText from "react-editext";
import Markdown from "react-markdown";
import { json } from "@remix-run/node";
import { useOutletContext } from "@remix-run/react";
import createServerSupabase from "utils/supabase.server";
import { SupabaseOutletContext } from "~/root";
import Like from "~/components/like";
import { Tooltip } from 'react-tooltip';

dayjs.extend(relativeTime);
library.add(fab, fas);

const formatDate = (date: Date) => {
  return dayjs(date).fromNow();
};

const formatPostDate = (dateString: string) => {
  const date = new Date(dateString);
  const real_time = date.getTime();
  const minutesOffset = new Date().getTimezoneOffset();

  return dayjs(new Date (real_time + (minutesOffset * -1 * 60 * 1000))).fromNow();
}  

export const action: ActionFunction = async ({ request }) => {
  try {
    const supabase = createServerSupabase({ request });
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      throw new Error("User not authenticated");
    }

    const formData = new URLSearchParams(await request.text());
    const post = formData.get("post");

    if (post) {
      await supabase.from("posts").insert({ content: post, user_id: user.id });
    }

    return json(null, { status: 200 });
  } catch (error) {
    return json({ error: error.message }, { status: 500 });
  }
};

export const loader: LoaderFunction = async ({ request }) => {
  const response = new Response();
  const supabase = createServerSupabase({ request, response });

  const posts = await supabase.from("posts_with_likes").select().order("id", { ascending: false });
  const likes = await supabase.from("likes").select();
  const replies = await supabase.from("replies").select("*").order("id", { ascending: true });
  const { data: { user } } = await supabase.auth.getUser();
  const profiles = await supabase.from("profiles").select();

  return {
    posts: posts.data,
    user,
    likes: likes.data,
    replies: replies.data || [],
    profiles: profiles.data,
  };
};

export default function UserPage() {
  const { supabase } = useOutletContext<SupabaseOutletContext>();
  const { user, posts, likes, replies, profiles } = useLoaderData();
  const [newPost, setNewPost] = useState("");
  const [error, setError] = useState(null);
  const [replyInputs, setReplyInputs] = useState({});

  const handlePostSubmit = async (e) => {
    e.preventDefault();
    try {
      const { data, error } = await supabase
        .from('posts')
        .insert([{ content: newPost, user_id: user.id }]);

      if (error) {
        throw error;
      }

      setNewPost('');
      console.log('Post submitted successfully:', data);
    } catch (error) {
      setError('Error submitting post: ' + error.message);
      console.error('Error submitting post:', error);
    }
  };

  const editPosts = async (content, postId) => {
    try {
      const { data, error } = await supabase
        .from('posts')
        .update({ content })
        .eq('id', postId);

      if (error) throw error;
      console.log('Post updated successfully:', data);
    } catch (error) {
      setError('Error updating post: ' + error.message);
      console.error('Error updating post:', error);
    }
  };

  const deletePost = async (postId) => {
    try {
      const { data, error } = await supabase
        .from('replies')
        .delete()
        .eq('post_id', postId)
        .then(() =>
          supabase
            .from('posts')
            .delete()
            .eq('id', postId)
        );

      if (error) throw error;

      console.log('Post and its replies deleted successfully:', data);
    } catch (error) {
      setError('Error deleting post: ' + error.message);
      console.error('Error deleting post:', error);
    }
  };

  const postReply = async (content, postId) => {
    try {
      const { data, error } = await supabase
        .from('replies')
        .insert([{ content, post_id: postId, user_id: user.id }]);

      if (error) throw error;
      console.log('Reply submitted successfully:', data);
    } catch (error) {
      setError('Error submitting reply: ' + error.message);
      console.error('Error submitting reply:', error);
    }
  };

  const toggleReplyInput = (postId) => {
    setReplyInputs((prev) => ({
      ...prev,
      [postId]: !prev[postId]
    }));
  };

  if (!user) {
    return <p className="text-white">You need to login to see this page.</p>;
  }

  return (
    <>
      {user && (
        <div className="cards flex">
          <img className="avatar" src={user.user_metadata.avatar_url} alt="User Avatar" />
          <Form className="postcontainer" method="post" onSubmit={handlePostSubmit}>
            <div className="postcontainer">
              <textarea
                id="clearPost"
                name="post"
                placeholder="What have you done today?"
                className="textarea postinput"
                value={newPost}
                onChange={(e) => setNewPost(e.target.value)}
              />
              <button className="button postsubmit" type="submit">
                Post
              </button>
              <p className="postmarkdown">
                <FontAwesomeIcon icon={["fab", "markdown"]} /> is supported
              </p>
            </div>
          </Form>
          {error && <div className="error">{error}</div>}
        </div>
      )}

      {posts.map((post) => (
        <div className="cards postcard" key={post.id}>
          <div className="flex">
            <div className="avatarcont ml-0 mr-0">
              <a href={`/${post.username}`}>
                <img className="avatar avatar3" src={post.avatar} alt={`${post.username} avatar`} />
              </a>
            </div>
            <div className="info ml-4">
              <h1 className="username mb-2 left">
                {post.displayname || post.username}{" "}
                <span className="handle">
                  {post.verified && (
                    <span className="verify">
                      <FontAwesomeIcon icon={["fas", "check"]} />
                    </span>
                  )}
                </span>
                <span className="handle">@{post.username}</span>
                <br />
                <a className="minutesago" href={`posts/${post.id}`}>
                  {formatPostDate(post.published_at)}
                </a>
              </h1>
              <br />
            </div>
          </div>
          <p className="postcontent grid">
            {post.user_id === user.id ? (
              <EdiText
                key={post.id}
                value={post.content}
                onSave={(value) => editPosts(value, post.id)}
                submitOnEnter
                type="textarea"
                renderValue={(value) => <Markdown>{value}</Markdown>}
              />
            ) : (
              <Markdown>{post.content}</Markdown>
            )}
          </p>
          <div className="replies">
            {replies
              .filter((reply) => reply.post_id === post.id)
              .map((reply) => {
                const userProfile = profiles.find((profile) => profile.id === reply.user_id);
                if (!userProfile) return null;
                return (
                  <div key={reply.id} className="postcontent mb-4">
                    <img
                      data-tooltip-id="avatarTooltip" 
                      data-tooltip-content={userProfile.username}
                      className="avatar avatar3"
                      src={userProfile.avatar}
                      alt={userProfile.username}
                    />
                    <Tooltip id="avatarTooltip" />
                    <p className="reply-content mt-3">{reply.content}</p>
                    <p>
                      <span className="reply-author minutesago mt-3">
                        {formatDate(reply.created_at)}
                      </span>
                    </p>
                  </div>
                );
              })}
          </div>
          <div>
            <span className="minutesago mt-6 mr-3">
              <Like postId={post.id} initialLikes={post.likes} />
            </span>
            <button className="minutesago" onClick={() => toggleReplyInput(post.id)}>
              reply
            </button>
          </div>
          {post.author_id === user.id && (
            <div>
              <button
                onClick={() => deletePost(post.id)}
                className="bg-red-500 text-gray-200 minutesago"
              >
                delete
              </button>
            </div>
          )}
          {replyInputs[post.id] && (
            <Form
              className="reply-form"
              onSubmit={(e) => {
                e.preventDefault();
                const formData = new FormData(e.target);
                const replyContent = formData.get("reply");
                postReply(replyContent, post.id);
              }}
            >
              <textarea
                name="reply"
                placeholder="Write a reply..."
                className="textarea reply-input"
              />
              <button type="submit" className="button reply-submit">
                Reply
              </button>
            </Form>
          )}
        </div>
      ))}
    </>
  );
}

// pages/home.vue
<template>
  <div>
    <div v-if="user" class="cards flex">
      <img class="avatar" :src="user.user_metadata.avatar_url" alt="User Avatar" />
      <form class="postcontainer" @submit.prevent="handlePostSubmit">
        <div class="postcontainer">
          <textarea
            id="clearPost"
            name="post"
            placeholder="What have you done today?"
            class="textarea postinput"
            v-model="newPost"
          />
          <button class="button postsubmit" type="submit">
            Post
          </button>
          <p class="postmarkdown">
            <font-awesome-icon :icon="['fab', 'markdown']" /> is supported
          </p>
        </div>
      </form>
      <div v-if="error" class="error">{{ error }}</div>
    </div>

    <div v-for="post in posts" :key="post.id" class="cards postcard">
      <div class="flex">
        <div class="flex-col ml-0 mr-0">
          <a :href="`/${post.username}`">
            <img class="avatar avatar3" :src="post.avatar" :alt="`${post.username} avatar`" />
          </a>
        </div>
        <div class="info flex ml-4">
          <h1 class="username mb-2 left">
            {{ post.displayname || post.username }}
            <span class="handle">
              <span v-if="post.verified" class="verify">
                <font-awesome-icon :icon="['fas', 'check']" />
              </span>
            </span>
            <span class="handle">@{{ post.username }}</span>
            <br />
            <a class="minutesago" :href="`posts/${post.id}`">
              {{ formatPostDate(post.published_at) }}
            </a>
          </h1>
          <br />
        </div>
      </div>
      <p class="postcontent grid">
        {{ post.content }}
      </p>
      <div class="replies">
        <div
          v-for="reply in replies.filter((reply) => reply.post_id === post.id)"
          :key="reply.id"
          class="postcontent mb-4"
        >
          <img
            v-if="reply.avatar"
            data-tooltip-id="avatarTooltip"
            :data-tooltip-content="reply.username"
            class="avatar avatar3"
            :src="reply.avatar"
            :alt="reply.username"
          />
          <tooltip id="avatarTooltip" />
          <p class="reply-content mt-3">{{ reply.content }}</p>
          <p>
            <span class="reply-author minutesago mt-3">
              {{ formatDate(reply.created_at) }}
            </span>
          </p>
        </div>
      </div>
      <div>
        <span class="minutesago mt-6 mr-3">
          <Like :postId="post.id" :initialLikes="post.likes" /> {{ post.likes }}
        </span>
        <button class="minutesago mr-3" @click="toggleReplyInput(post.id)">
          reply
        </button>
        <button v-if="post.author_id === user.id" @click="deletePost(post.id)" class="bg-red-500 text-gray-200 minutesago">
          delete
        </button>
      </div>
      <form v-if="replyInputs[post.id]" class="reply-form" @submit.prevent="handleReplySubmit(post.id)">
        <textarea name="reply" placeholder="Write a reply..." class="textarea reply-input" v-model="replyContent" />
        <button type="submit" class="button reply-submit">Reply</button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime);

const supabase = useSupabaseClient();
const user = useSupabaseUser();

const posts = ref([]);
const replies = ref([]);
const newPost = ref('');
const error = ref<string | null>(null);
const replyInputs = reactive<Record<number, boolean>>({});
const replyContent = ref('');

onMounted(async () => {
  await fetchPosts();
  await fetchReplies();
});

async function fetchPosts() {
  try {
    const { data, error: fetchError } = await supabase.from('posts_with_likes').select().order('id', { ascending: false });
    if (fetchError) {
      throw fetchError;
    }
    posts.value = data;
  } catch (err) {
    console.error('Error fetching posts:', err.message);
  }
}

async function fetchReplies() {
  try {
    const { data, error: fetchError } = await supabase.from('reply_with_profile').select('*').order('id', { ascending: true });
    if (fetchError) {
      throw fetchError;
    }
    replies.value = data;
  } catch (err) {
    console.error('Error fetching replies:', err.message);
  }
}

function formatDate(date: string) {
  return dayjs(date).fromNow();
}

function formatPostDate(dateString: string) {
  const date = new Date(dateString);
  const real_time = date.getTime();
  const minutesOffset = new Date().getTimezoneOffset();
  return dayjs(new Date(real_time + minutesOffset * -1 * 60 * 1000)).fromNow();
}

async function handlePostSubmit() {
  try {
    if (!user.value) {
      throw new Error('User not authenticated');
    }
    const { data, error: postError } = await supabase.from('posts').insert([{ content: newPost.value, user_id: user.value.id }]);
    if (postError) {
      throw postError;
    }
    newPost.value = '';
    await fetchPosts(); // Refresh posts after submission
    console.log('Post submitted successfully:', data);
  } catch (err) {
    error.value = 'Error submitting post: ' + err.message;
    console.error('Error submitting post:', err);
  }
}

async function editPosts(content: string, postId: number) {
  try {
    const { data, error: editError } = await supabase.from('posts').update({ content }).eq('id', postId);
    if (editError) throw editError;
    await fetchPosts(); // Refresh posts after editing
    console.log('Post updated successfully:', data);
  } catch (err) {
    error.value = 'Error updating post: ' + err.message;
    console.error('Error updating post:', err);
  }
}

async function deletePost(postId: number) {
  try {
    const { error: deleteRepliesError } = await supabase.from('replies').delete().eq('post_id', postId);
    if (deleteRepliesError) throw deleteRepliesError;

    const { data, error: deletePostError } = await supabase.from('posts').delete().eq('id', postId);
    if (deletePostError) throw deletePostError;

    await fetchPosts(); // Refresh posts after deletion
    console.log('Post and its replies deleted successfully:', data);
  } catch (err) {
    error.value = 'Error deleting post: ' + err.message;
    console.error('Error deleting post:', err);
  }
}

async function postReply(content: string, postId: number) {
  try {
    if (!user.value) {
      throw new Error('User not authenticated');
    }
    const { data, error: replyError } = await supabase.from('replies').insert([{ content, post_id: postId, user_id: user.value.id }]);
    if (replyError) throw replyError;
    await fetchReplies(); // Refresh replies after submission
    console.log('Reply submitted successfully:', data);
  } catch (err) {
    error.value = 'Error submitting reply: ' + err.message;
    console.error('Error submitting reply:', err);
  }
}

function toggleReplyInput(postId: number) {
  replyInputs[postId] = !replyInputs[postId];
}

async function handleReplySubmit(postId: number) {
  try {
    await postReply(replyContent.value, postId);
    replyContent.value = '';
  } catch (err) {
    error.value = 'Error submitting reply: ' + err.message;
    console.error('Error submitting reply:', err);
  }
}

watchEffect(() => {
  if (!user.value) {
    return navigateTo('/login')
  }
})
</script>

<style scoped>
/* Add your styles here */
</style>
