// app/routes/login.tsx
import { useOutletContext } from "@remix-run/react";
import type { SupabaseOutletContext } from "~/root";

export default function Login() {
  
  const {supabase} = useOutletContext<SupabaseOutletContext>();
  
    const handleDiscordLogin = async () => {
      const {error} = await supabase.auth.signInWithOAuth({
        provider: 'discord'
      })

      if (error) {
        console.log(error);
      }
    }
  
    const handleLogout = async () => {
      const { error } = await supabase.auth.signOut();

      if (error) {
        console.log(error);
      }
    }
  
    return (
      <>
        <button onClick={handleDiscordLogin}>Discord Login</button>
        <button onClick={handleLogout}>Logout</button>
      </>
    )
  }

// pages/login.vue
<template>
    <div class="flex items-center justify-center min-h-screen">
        <button class="button blurple" @click="signInWithOAuth">
          <Icon name="fa6-brands:discord" class="navicon"/> Login With Discord
        </button>
    </div>
</template>

<script setup lang="ts">
const supabase = useSupabaseClient()
const user = useSupabaseUser()

const signInWithOAuth = async () => {
  const { error } = await supabase.auth.signInWithOAuth({
    provider: 'discord',
    options: {
      redirectTo: '/dashboard',
    },
  })
  if (error) console.log(error)
}

const signOut = async () => {
  const { error } = await supabase.auth.signOut()
  if (error) console.log(error)
}

if (user.value) {
  navigateTo('/dashboard')
}
</script>

<style scoped>

</style>
